#!/usr/bin/env bash
set -eu

# oyster-modules setup script

REPOSITORY="https://github.com/ryuzi/oyster-modules.git"
PREFIX_DEFAULT="${HOME:?}"
OYST_CONFIG="${PREFIX_DEFAULT}/.oyster/config"
OYST_MODULE_PATH="${PREFIX_DEFAULT}/.oyster/vendor/modules"

# check oyster config
{
    [ -s "${OYST_CONFIG}" ] && echo "> ${OYST_CONFIG} ok."
}

# check installation directory
{
    if [ ! -e "${PREFIX_DEFAULT}/.oyster/config" ]; then
        echo "> oyster is not installed!"
        echo
        exit 1
    fi
    if [ -e "${OYST_MODULE_PATH}" ]; then
        echo "> '${OYST_MODULE_PATH}' already exists!"
        echo
        exit 1
    fi
}

# check git command
{
    if type git; then
        : # no problem.
    else
        echo "> please install git."
        echo
        exit 1
    fi
}

# download oyster-modules
{
    cd "${PREFIX_DEFAULT}"
    git clone "${REPOSITORY}" .oyster/vendor
    cd -
}

# write initial setting for .oystrc
echo "> please add the following settings for oyster-modules to the top of your ${PREFIX_DEFAULT}/.oyster/config file:"
{
    echo
    echo
    echo "export OYST_MODULE_PATH=${OYST_MODULE_PATH}"
    echo
    echo
}

echo "> complete setup oyster-modules."
