#!/usr/bin/env bash
set -eu

# oyster-modules setup script

REPOSITORY="https://github.com/ryuzi/oyster-modules.git"
PREFIX_DEFAULT="${HOME:?}"
OYSTERC="${PREFIX_DEFAULT}/.oysterc"

# check .oysterc
{
    [ -s "${OYSTERC}" ] && echo "> ${OYSTERC} ok."
}

# check installation directory
{
    if [ -e "${PREFIX_DEFAULT}/.oyster-modules" ]; then
        echo "> '${PREFIX_DEFAULT}/.oyster-modules' already exists!"
        echo
        exit 1
    fi
}

# check git command
{
    if type git; then
        : # no problem.
    else
        echo "> please install git."
        echo
        exit 1
    fi
}

# download oyster-modules
{
    cd "${PREFIX_DEFAULT}"
    git clone "${REPOSITORY}" .oyster-modules
    cd -
}

# write initial setting for .oystrc
echo "> please add the following settings for oyster-modules to the top of your ${PREFIX_DEFAULT}/.oysterc file:"
{
    echo
    echo
    echo "export OYST_MODULE_PATH=${PREFIX_DEFAULT}/.oyster-modules"
    echo
    echo
}

echo "> complete setup oyster-modules."
