#!/usr/bin/env bash
set -eu

# oyster-modules setup script

REPOSITORY="git@github.com:ryuzi/oyster-modules.git"
PREFIX_DEFAULT="${HOME:?}"
OYSTERC="${PREFIX_DEFAULT}/.oysterc"

# check .oysterc
{
    [ -s "${OYSTERC}" ] && echo "> ${OYSTERC} ok."
}

# check installation directory
{
    echo -n "> install directory[ $PREFIX_DEFAULT ]: "
    read -r INPUT
    prefix="${INPUT:-$PREFIX_DEFAULT}"
    if [ -e "${prefix}/.oyster-modules" ]; then
        echo "> '${prefix}/.oyster-modules' already exists!"
        echo
        exit 1
    fi
}

# check git command
{
    if type git; then
        : # no problem.
    else
        echo "> please install git."
        echo
        exit 1
    fi
}

# download oyster-modules
{
    cd "${prefix}"
    git clone "${REPOSITORY}" .oyster-modules
    cd -
}

# write initial setting for .oystrc
echo "> please add the following settings for oyster-modules to the top of your ${prefix}/.oysterc file:"
{
    echo
    echo
    echo "export OYST_MODULE_PATH=${prefix}/.oyster-modules"
    echo
    echo
}

echo "> complete setup oyster-modules."
